version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'django_project'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'greatrun'